export enum ProtectionType {
    FIRE_PROTECTION = 'FIRE_PROTECTION',
    GLASS_PROTECTION = 'GLASS_PROTECTION',
    LEAKS_PROTECTION = 'LEAKS_PROTECTION',
    MOTION_PROTECTION = 'MOTION_PROTECTION'
}